FROM php:7.0-fpm

MAINTAINER Vitams <vmpartner@gmail.com>

RUN apt-get update && apt-get install -y \
    libpq-dev \
    libmemcached-dev \
    curl \
    wget \
    libjpeg-dev \
    libpng12-dev \
    libfreetype6-dev \
    libssl-dev \
    libmcrypt-dev \
    --no-install-recommends \
    && rm -r /var/lib/apt/lists/*

# install mcrypt library
RUN docker-php-ext-install mcrypt

# configure gd library
RUN docker-php-ext-configure gd \
    --enable-gd-native-ttf \
    --with-jpeg-dir=/usr/lib \
    --with-freetype-dir=/usr/include/freetype2

# Install extensions using the helper script provided by the base image
RUN docker-php-ext-install \
    opcache \
    mysqli \
    gd \
    pdo_mysql


RUN apt-get update && apt-get install -y \
    libicu-dev \
    zlib1g-dev \
    g++ \
  && rm -r /var/lib/apt/lists/* \
  && docker-php-ext-configure intl \
  && docker-php-ext-install intl

RUN apt-get update && apt-get install -y \
    libc-client-dev \
    libkrb5-dev \
    libldap2-dev \
  && rm -r /var/lib/apt/lists/* \
  && docker-php-ext-configure ldap --with-libdir=lib/x86_64-linux-gnu \
  && docker-php-ext-configure imap --with-kerberos --with-imap-ssl \
  && docker-php-ext-install ldap imap

RUN apt-get update && apt-get install -y \
      libxml2-dev \
  && rm -r /var/lib/apt/lists/* \
  && docker-php-ext-install soap

RUN apt-get update && apt-get install -y \
      sqlite3 \
      libsqlite3-dev \
      libsqlite3-0 \
  && rm -r /var/lib/apt/lists/* \
  && docker-php-ext-install pdo_sqlite

RUN apt-get update && apt-get install -y \
    libpspell-dev \
  && rm -r /var/lib/apt/lists/* \
  && docker-php-ext-install pspell

#RUN wget https://github.com/websupport-sk/pecl-memcache/archive/NON_BLOCKING_IO_php7.tar.gz \
#    && tar -zxvf NON_BLOCKING_IO_php7.tar.gz \
#    && cd pecl-memcache-NON_BLOCKING_IO_php7 \
#    && phpize && ./configure --enable-memcache && make \
#    && cp modules/memcache.so /usr/local/lib/php/extensions/no-debug-non-zts-20151012/ \
#    && docker-php-ext-enable memcache \
#    && rm -rf NON_BLOCKING_IO_php7.zip \
#    && rm -rf pecl-memcache-NON_BLOCKING_IO_php7

RUN apt-get update && apt-get install -y \
      git \
    && rm -r /var/lib/apt/lists/* \
    && git clone -b php7 https://github.com/php-memcached-dev/php-memcached.git /usr/src/php/ext/memcached \
    && cd /usr/src/php/ext/memcached \
    && git checkout origin/php7 \
    && docker-php-ext-configure memcached \
    && docker-php-ext-install memcached \
    && apt-get autoremove -y

# Install Composer
ENV COMPOSER_PATH /etc/composer
RUN rm -rf $COMPOSER_PATH \
    && mkdir -p $COMPOSER_PATH \
    && cd $COMPOSER_PATH \
    && curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer

# Install xdebug
#RUN pecl install xdebug && docker-php-ext-enable xdebug

RUN docker-php-ext-install zip

RUN apt-get update \
  && apt-get install -y -q --no-install-recommends \
    ssmtp \
  && apt-get clean \
  && rm -r /var/lib/apt/lists/*

COPY ./ssmtp.conf /etc/ssmtp/ssmtp.conf

ADD ./bitrix.ini /usr/local/etc/php/conf.d/

ADD ./laravel.pool.conf /usr/local/etc/php-fpm.d/www.conf

#RUN usermod -u 1000 www-data
RUN useradd --shell /bin/bash -u 1000 -o -c "" -m docker-www-data
RUN usermod -u 1000 docker-www-data

WORKDIR /var/www/site

EXPOSE 9000

CMD ["php-fpm"]
